yeongkkeul/yeongkkuel-server

src/main/java/com/umc/yeongkkeul/domain/ChatRoom.java, src/main/java/com/umc/yeongkkeul/domain/Message.java, src/main/java/com/umc/yeongkkeul/domain/User.java
22-fix-채팅-entity-수정
- Message와 같이 채팅 내역과 관련된 데이터를 Redis에 저장할 계획이기에 주석 처리했습니다.
- Message와 관련된 코드(객체 그래프 탐색)도 주석 처리 했습니다.
- 추후에 Redis에 저장하기 위한 dto record를 추가할 계획입니다.
=> [FIX] Message Entity와 관련 객체 그래프 탐색 코드 제거

src/main/java/com/umc/yeongkkeul/security/FindLoginUser.java, src/main/java/com/umc/yeongkkeul/web/controller/CategoryController.java
#40 
- email 값을 반환하던 getCurrentUserId()의 값을 toId로 user의 Id로 리턴하도록 변환로직 추가
- getCurrentUserId()의 로직 자체를 수정하지 않은 이유는 해당 로직으로 이미 구현된 서비스가 존재
Long userId = toId(getCurrentUserId()); -> userId 값
=> fix: Email을 userId로 바꾸는 로직 추가 #40

src/main/java/com/umc/yeongkkeul/YeongkkeulApplication.java, src/main/java/com/umc/yeongkkeul/domain/Reward.java, src/main/java/com/umc/yeongkkeul/domain/enums/RewardType.java, src/main/java/com/umc/yeongkkeul/service/RewardCommandService.java, src/main/java/com/umc/yeongkkeul/web/dto/RewardRequestDto.java, src/main/java/com/umc/yeongkkeul/web/dto/RewardResponseDto.java
#44 
- 리워드 발급 메서드 구현
- createdAt 반영 위해 @EnableJpaAuditing 어노테이션 추가
- 이름 충돌해서 ReasonCode -> RewardType 변경
리워드 발급 기준에 맞게 넣어서 메소드 사용
```
RewardRequestDto rewardRequestDto = RewardRequestDto.builder
.rewardType(RewardType.INDIVIDUAL)       
.description("식비에서 연속 5일 무지출 달성")       
.amount(10)        
.build();
rewardCommandService.saveReward(userId, rewardRequestDto);
```
=> feat: 리워드 발급 메서드 구현 #44

src/main/java/com/umc/yeongkkeul/aws/s3/AmazonS3Manager.java, src/main/java/com/umc/yeongkkeul/converter/MultipartJackson2HttpMessageConverter.java, src/main/java/com/umc/yeongkkeul/repository/RewardRepository.java, src/main/java/com/umc/yeongkkeul/service/MyPageCommandService.java, src/main/java/com/umc/yeongkkeul/service/MyPageQueryService.java, src/main/java/com/umc/yeongkkeul/web/controller/MyPageController.java, src/main/java/com/umc/yeongkkeul/web/dto/MyPageInfoRequestDto.java, src/main/java/com/umc/yeongkkeul/web/dto/MyPageInfoResponseDto.java
#66
- 프로필 사진 s3 통해 file로 받게 수정
- swagger에서 multipart/form-data인식 못하는 문제 해결 위해 MultipartJackson2HttpMessageConverter 추가
- 리워드 목록 조회 수정  (최근 7일 최신순 정렬)
- 하루 목표 지출액 수정 api 구현 
- 하루 목표 지출액 null일 때 weeklyAchievementRate도 null로 반환되도록 Double타입으로 변경
=> feat: 마이페이지 api 수정 # 66

src/main/java/com/umc/yeongkkeul/apiPayload/code/status/ErrorStatus.java, src/main/java/com/umc/yeongkkeul/aws/s3/AmazonS3Manager.java, src/main/java/com/umc/yeongkkeul/service/ChatService.java, src/main/java/com/umc/yeongkkeul/web/controller/ChatAPIController.java, src/main/java/com/umc/yeongkkeul/web/controller/ChatController.java
#63 
- S3 Manager에 다운로드 기능 추가 및 원본 데이터의 메타데이터 정보 저장
- 채팅 메시지를 Get하는 로직을 활용하여, 이미지 타입인 이미지 메시지들 조회(이미지 메시지의 content에는 s3 저장 필요)
- 이미지를 다운로드하는 API 추가하여, 원본데이터와 같은 ContentType으로 다운로드 가능 
- 프론트에서 이미지 업로드 api를 활용해, 이미지 업로드를 진행
- 업로드한 이미지의 S3 주소를 받아서, 채팅 메시지를 전송(타입을 이미지로 지정)
- 서랍기능을 위해 이미지 get으로 이미지 메시지만 조회
- 이미지 메시지 다운 api를 사용해 필요시, 다운
=> feat: 채팅방 서랍 기능 api 구현

src/main/java/com/umc/yeongkkeul/apiPayload/code/status/ErrorStatus.java, src/main/java/com/umc/yeongkkeul/repository/CategoryRepository.java, src/main/java/com/umc/yeongkkeul/service/CategoryCommandServiceImpl.java, src/main/java/com/umc/yeongkkeul/service/ExpenseCommandServiceImpl.java
#96 
- 카테고리 삭제시, 종속된 지출 내역을 임시 카테고리에 보존하도록 로직변경
- 임시 카테고리 trash가 존재하는지 확인 후 없다면 생성(유저 내에서 이름이 고유하도록 개발해놔서 가능)
- 지우려던 카테고리의 지출 내역을 모두 유저의 trash에 이전
- 카테고리 삭제
민지님 양방향 연관관계 설정을 추가해서, 지출이 생성될 때 카테고리의 list안에 값을 추가하도록 변경했습니다~
=> feat: 카테고리 삭제시, 종속된 지출 내역을 임시 카테고리에 보존하도록 로직변경

build.gradle, src/main/java/com/umc/yeongkkeul/converter/ChatRoomConverter.java, src/main/java/com/umc/yeongkkeul/domain/mapping/ChatRoomMembership.java, src/main/java/com/umc/yeongkkeul/repository/ChatRoomMembershipRepository.java, src/main/java/com/umc/yeongkkeul/repository/ChatRoomRepository.java, src/main/java/com/umc/yeongkkeul/service/ChatService.java, src/main/java/com/umc/yeongkkeul/web/controller/ChatAPIController.java, src/main/java/com/umc/yeongkkeul/web/controller/ChatController.java, src/main/java/com/umc/yeongkkeul/web/dto/chat/ChatRoomInfoResponseDto.java, src/main/java/com/umc/yeongkkeul/web/dto/chat/MessageDto.java
#91 
- 테스트 진행하고 제가 머지하겠습니다!
- 테스트 하면서 주석 추가하겠습니다.
=> [FIX] 채팅 내역, 채팅방 정보 동기화(조회) 수정

src/main/java/com/umc/yeongkkeul/converter/CategoryConverter.java, src/main/java/com/umc/yeongkkeul/web/dto/ExpenseResponseDTO.java
#103 
- 홈 화면 - 지출 목록 조회 시 첨부된 사진 유무 반환하도록 수정
- 카테고리별 지출 목록 조회 시 첨부된 사진 유무 반환하도록 수정
=> fix: 지출 목록 조회 시 첨부된 사진 유무 반환하도록 수정

src/main/java/com/umc/yeongkkeul/converter/CategoryConverter.java, src/main/java/com/umc/yeongkkeul/web/dto/CategoryResponseDTO.java
#106 
- 홈 화면, 카테고리별 지출 기록 조회, 주간 통계 조회 시 카테고리 id도 반환하도록 수정
=> fix: 지출 목록 조회 시 카테고리 id도 반환하도록 수정

src/main/java/com/umc/yeongkkeul/service/ChatService.java, src/main/java/com/umc/yeongkkeul/web/controller/ChatAPIController.java, src/main/java/com/umc/yeongkkeul/web/dto/chat/ImageChatRequestDTO.java
#108 
- 사진 업로드 컨트롤러 api의 reqParam -> reqBody로 수정
- consumes 조건 추가
- 현재 로컬에서 잡히는 것 확인했고, 받은 이미지 url을 채팅으로 바로 쏴주도록 구현해주셔야합니다!
- 이는 업로드 로직일뿐이고, 저희 백에서 관리하는 방식이 이미지 url을 채팅 content로 넣어서 서랍기능을 구현하고 있습니다.
- 그리고 TYPE의 경우도 "IMAGE"로 넣어주셔야합니다.
=> fix: 컨트롤러 reqBody로 변경 및 MultipartFile 적용 확인

src/main/java/com/umc/yeongkkeul/config/WebSocketBrokerConfig.java, src/main/java/com/umc/yeongkkeul/service/ChatService.java, src/main/java/com/umc/yeongkkeul/socket/SocketConnectionTracker.java, src/main/java/com/umc/yeongkkeul/socket/SocketSessionInterceptor.java
#99 
- ChannelInterceptor 기반 소켓 연결 상태 추적 로직 구현
- 가입 정보와 구독 상태의 분리 관리
- 메시지 전송 로직 분기 처리
Redis key 네이밍이나 온라인 상태 저장 방식(TTL 적용 여부 등)에 대해 개선할 부분이 있는지 확인 부탁
채팅 전송의 서비스 로직 변환에 대해서 의견 듣고 싶습니다~
=> feat: channelinterceptor를 기반한 socket의 연결 상태 추적 로직 추가

src/main/java/com/umc/yeongkkeul/service/ExpenseQueryServiceImpl.java, src/main/java/com/umc/yeongkkeul/web/dto/ExpenseResponseDTO.java
#124 
- 지출 월간 달력 - 하루 목표 지출액도 포함하여 반환하도록 수정
=> fix: 지출 월간 달력 - 하루 목표 지출액도 포함하여 반환하도록 수정

src/main/java/com/umc/yeongkkeul/config/RabbitMQConfig.java, src/main/java/com/umc/yeongkkeul/service/ChatService.java, src/main/java/com/umc/yeongkkeul/web/controller/ChatController.java
#118 
- RabbitMQ의 메시지를 소비하지 않으면 큐에 메시지가 쌓여 RabbitMQ의 메모리에 부담이 됩니다.
- 그렇기에 consumer를 추가하여 메시지를 비우고 비동기적으로 redis에 메시지를 저장하는 로직을 구현합니다.
- **현재 단계에서는 비동기적으로 저장하는 로직을 구현하지 않고 클라이언트와 연동한 다음에 구현하겠습니다.** 
- 메시지가 정상적으로 RabbitMQ에 전송되었는지, 정상적으로 해당 큐로 전송이 되었는지 확인하는 코드를 작성했습니다.
- 그리고 추후에 재전송 로직을 추가할 예정입니다.
- WebSocket을 통해 접속한 사용자의 세션 ID를 로그에 기록합니다.
=> [FEAT] rabbitmq consumer 추가 세션 관리

src/main/java/com/umc/yeongkkeul/batch/BatchScheduler.java, src/main/java/com/umc/yeongkkeul/batch/ChatRoomBatchConfig.java, src/main/java/com/umc/yeongkkeul/batch/ChatRoomScoreBatchConfig.java, src/main/java/com/umc/yeongkkeul/domain/ChatRoom.java, src/main/java/com/umc/yeongkkeul/repository/ChatRoomRepository.java, src/main/java/com/umc/yeongkkeul/service/ChatRoomQueryService.java, src/main/java/com/umc/yeongkkeul/web/dto/BannerResponseDto.java
#120
- ChatRoom엔티티에 achievedCount(목표 달성 인원), averageExpense(챌린저 지출 평균), ranking(채팅방 백분위) 컬럼 추가
- 추가한 엔티티 관련 데이터 스프링 배치 작업
- ranking은 정책상 채팅방 인원 5명 이상일 때만 집계되기 때문에 5명 이하인 경우 null 처리
- 나이대, 직업 설정 -> 설정된 필터 채팅방 내 순위
- 나이대, 직업 설정 x -> 전체 채팅방 내 순위
- 배치된 데이터 바탕으로 채팅방 배너 조회 api 로직 수정 
테스트는 완료했으나, 쿼리 정리(최적화)가 필요해 리팩토링 예정
=> feat: 채팅방 정보 조회 시 필요 데이터 갱신 #120

src/main/java/com/umc/yeongkkeul/service/ChatService.java, src/main/java/com/umc/yeongkkeul/web/controller/ChatAPIController.java
#136 
- 채팅방 이미지 업로드 이후, 채팅방 전송로직 추가
- 기존에는 이미지를 업로드한 뒤 이미지 URL만 반환하는 방식이었습니다. 이번에 메시지 전송 로직(sendImageChat)을 함께 추가하여, 이미지가 업로드되면 해당 이미지를 자동으로 채팅방에 전송하도록 구현하였습니다. 이를 통해 사용자는 업로드된 이미지를 별도의 추가 액션 없이 바로 채팅 내에서 확인할 수 있으며, 프론트엔드에서는 “서랍 기능”에만 집중할 수 있도록 개선하였습니다.
=> feat: 채팅방 이미지 업로드 이후, 채팅방 전송로직 추가

src/main/java/com/umc/yeongkkeul/repository/UserRepository.java, src/main/java/com/umc/yeongkkeul/service/GoogleLoginService.java, src/main/java/com/umc/yeongkkeul/service/KakaoLoginService.java, src/main/java/com/umc/yeongkkeul/web/dto/SocialInfoResponseDto.java
#140 
- 로그인 시, 해당 유저의 userId값도 리턴하도록 dto 추가 및 서비스 로직 변경
- 기존 유저의 경우도 refreshToekn을 업데이트해서, 재발급 이슈에 대해서 정상적으로 돌아가도록 변경
기존 로그인 로직과 비교해서, 변경사항 있는 지 점검 부탁드립니다.
=> feat: 로그인시 해당 유저의 userId 추가로 리턴하도록 로직 변경

src/main/java/com/umc/yeongkkeul/domain/Category.java
#163 
- Category 엔티티의 expenseList에 @Builder.Default를 추가하여 컬렉션 필드 기본값을 new ArrayList<>()로 설정.
=> fix: 카테고리가 지니고 있는 expenseList 필드를 빌더에서 초기화 보장하도록 Default 지정

src/main/java/com/umc/yeongkkeul/apiPayload/code/status/ErrorStatus.java, src/main/java/com/umc/yeongkkeul/repository/CategoryRepository.java, src/main/java/com/umc/yeongkkeul/service/CategoryCommandServiceImpl.java
#172 
- countByUser(User user)를 통해, 카테고리수 생성시마다 점검
- 카테고리 생성시, 기존 6개이상이 이미 존재하면 에러 던지도록 로직 수정
=> feat: 카테고리 생성시, 최대개수 반영

src/main/java/com/umc/yeongkkeul/domain/Category.java, src/main/java/com/umc/yeongkkeul/domain/User.java, src/main/java/com/umc/yeongkkeul/repository/ExpenseRepository.java, src/main/java/com/umc/yeongkkeul/service/ExpenseCommandServiceImpl.java
#166 
- 무지출을 추적해서 포인트 추가하고, 알림 날리기!
- 하루에 하나 이상의 무지출/지출 기록이 있을 경우, 추가 무지출 입력 시 연속 무지출 일수를 증가시키지 않도록 수정
- `ExpenseRepository`에 `countByUserAndDay(user, currentDay)` 메서드 추가
- `updateConsecutiveNoSpendingDays()` 내에서 오늘 이미 지출(무지출 포함) 기록이 있으면 연속 무지출 로직 무시
- 기존 어제 무지출 확인 로직(`existsNoSpendingExpense`)은 그대로 유지
- 리워드 내역 추가
- 리워드 유저 잔액 반영
=> feat: 카테고리 n일 연속 무지출 달성 리워드 지급

src/main/java/com/umc/yeongkkeul/domain/User.java, src/main/java/com/umc/yeongkkeul/repository/ExpenseRepository.java, src/main/java/com/umc/yeongkkeul/service/NotificationService.java, src/main/java/com/umc/yeongkkeul/web/controller/ExpenseController.java
#174 
- 지출 생성 또는 수정 - 하루 목표 지출액 초과 알림 생성
- 초과되는 처음에만 알림이 생성되도록 함
- 하루 목표 지출액이 설정되어 있지 않은 유저라면 알림 생성 X
- 해당 지출 기록의 날짜가 오늘이 아닌 경우 알림 생성 X
=> [FEAT] 하루 목표 지출액 초과 알림 생성

src/main/java/com/umc/yeongkkeul/repository/ExpenseRepository.java, src/main/java/com/umc/yeongkkeul/service/ExpenseCommandServiceImpl.java
#166 
- 무지출 추적 로직을 카테고리 각각 적용하도록 변경
=> fix: 카테고리 각각 적용하도록 로직 변경

src/main/java/com/umc/yeongkkeul/web/controller/ChatAPIController.java
#136 
- 이미지 업로드 reqBody 대신 reqParam으로 변경
@RequestBody는 요청 내용을 객체로 바인딩하기 위함. 이미지가 포함되는 경우 사용하면  415의 지원되지 않은 파일형식 에러를 발생시키게 됨. 따라서 파일만 필요한 경우는 @RequestParam을 사용하고, 미디어파일 외의 복합적인 데이터가 필요하면 @RequestPart를 사용해야함. 굳이 DTO를 통해서 함께 묶고 싶다면, ReqBody가 아니라 @ModelAttribute를 사용해야함.
=> fix: 이미지 업로드 reqBody 대신 reqParam으로 변경

src/main/java/com/umc/yeongkkeul/service/ChatService.java, src/main/java/com/umc/yeongkkeul/web/controller/ChatAPIController.java, src/main/java/com/umc/yeongkkeul/web/dto/chat/ImageChatResponseDTO.java
#181 
- 채팅방 이미지 다운로드시, 이미지 url을 파싱해서 key로 변환해서 사용하도록 로직 수정
- 채팅방 내 이미지 조회시, id값 추가
=> fix: 채팅방 이미지 다운로드 수정 및 이미지 채팅 조회 리턴값 id 추가

src/main/java/com/umc/yeongkkeul/service/ChatService.java, src/main/java/com/umc/yeongkkeul/web/dto/chat/MessageDto.java
#182 
- 채팅방 메시지 id값 불일치 현상 직렬화 문제 해결
- 다운로드 로직 보강 (버그는 없었음)
Comparing: m.id()=680121464358249748 (class java.lang.Long) vs messageId=680121464358249700 (class java.lang.Long)
위 값 중 프론트에서 api를 통해 조회했던 값인 우측 값이 정확도 문제로 값이 유실된 점을 확인할 수 있음. 키값이 크기 때문에 변형가능성이 있어 Json 직렬화 과정 중 String으로 변경했음.
=> fix: 채팅방 메시지 id값 불일치 현상 직렬화 문제 해결
