build.gradle, src/main/java/com/umc/yeongkkeul/config/SecurityConfig.java, src/main/java/com/umc/yeongkkeul/domain/User.java, src/main/java/com/umc/yeongkkeul/domain/common/BaseEntity.java, src/main/java/com/umc/yeongkkeul/security/JwtAuthenticationFilter.java, src/main/java/com/umc/yeongkkeul/security/TokenProvider.java, src/main/resources/application.yml
#3 
- Security 설정 추가
- 빈폴더 유지 위한 .gitkeep 추가 (파일 추가시 삭제 요망)
- JWT 토큰 생성 및 검증 로직 추가 (userId 기반, 추후 OAuth로 변경시 수정 필요)
=> feat: Security 설정 및 빈폴더 유지 #3

src/main/java/com/umc/yeongkkeul/domain/Reward.java, src/main/java/com/umc/yeongkkeul/domain/User.java, src/main/java/com/umc/yeongkkeul/domain/enums/AgeGroup.java, src/main/java/com/umc/yeongkkeul/domain/enums/Job.java, src/main/java/com/umc/yeongkkeul/domain/enums/UserRole.java
#6 
- User 엔티티 추가
- Reward 엔티티 추가
- 양방향 연관관계 맵핑
=> feat: User, Reward 엔티티 추가 #6

src/main/java/com/umc/yeongkkeul/domain/Category.java, src/main/java/com/umc/yeongkkeul/domain/Expense.java, src/main/java/com/umc/yeongkkeul/domain/Term.java, src/main/java/com/umc/yeongkkeul/domain/User.java, src/main/java/com/umc/yeongkkeul/domain/enums/Color.java, src/main/java/com/umc/yeongkkeul/domain/enums/TermType.java, src/main/java/com/umc/yeongkkeul/domain/mapping/UserTerms.java
#9 
- UserTerms, Term, Category, Expense 엔티티 추가
- 연관관계 설정
=> feat: UserTerms, Term, Category, Expense 엔티티 추가 #9

src/main/java/com/umc/yeongkkeul/domain/Item.java, src/main/java/com/umc/yeongkkeul/domain/Notification.java, src/main/java/com/umc/yeongkkeul/domain/enums/ItemType.java, src/main/java/com/umc/yeongkkeul/domain/enums/NotificationType.java, src/main/java/com/umc/yeongkkeul/domain/mapping/Purchase.java
=> [FEAT] 상점 아이템, 아이템 구매 이력 Entity 추가

src/main/java/com/umc/yeongkkeul/domain/Notification.java, src/main/java/com/umc/yeongkkeul/domain/mapping/Purchase.java
=> [FIX] Notification Entity 수정

build.gradle, src/main/java/com/umc/yeongkkeul/config/SecurityConfig.java, src/main/java/com/umc/yeongkkeul/config/SwaggerConfig.java, src/main/java/com/umc/yeongkkeul/config/WebConfig.java, src/main/java/com/umc/yeongkkeul/domain/enums/AgeGroup.java, src/main/java/com/umc/yeongkkeul/domain/enums/Job.java, src/main/java/com/umc/yeongkkeul/repository/UserRepository.java, src/main/java/com/umc/yeongkkeul/security/JwtAuthenticationFilter.java, src/main/java/com/umc/yeongkkeul/security/TokenProvider.java, src/main/java/com/umc/yeongkkeul/service/KakaoLoginService.java, src/main/java/com/umc/yeongkkeul/web/controller/UserController.java, src/main/java/com/umc/yeongkkeul/web/dto/KakaoInfoResponseDto.java, src/main/java/com/umc/yeongkkeul/web/dto/KakaoTokenResponseDto.java, src/main/resources/application.yml
ex)  #5 
- 카카오 소셜 로그인, Spring Security 설정
- Dependencies 추가
=> FEAT: "카카오 로그인 구현 및 SecurityConfig, Dependencies 추가" #5

.gitignore, src/main/java/com/umc/yeongkkeul/security/FindLoginUser.java, src/main/java/com/umc/yeongkkeul/security/TokenProvider.java, src/main/java/com/umc/yeongkkeul/service/AuthCommandService.java, src/main/java/com/umc/yeongkkeul/service/KakaoLoginService.java, src/main/java/com/umc/yeongkkeul/web/controller/UserController.java, src/main/java/com/umc/yeongkkeul/web/dto/KakaoInfoResponseDto.java, src/main/java/com/umc/yeongkkeul/web/dto/TokenDto.java, src/main/java/com/umc/yeongkkeul/web/dto/UserRequestDto.java
- gitignore추가
- refreshToken 구현중
=> FIX: "yml gitignore 설정 및 refreshToken 구현중"

src/main/java/com/umc/yeongkkeul/config/TestDataInitializer.java, src/main/java/com/umc/yeongkkeul/domain/Reward.java, src/main/java/com/umc/yeongkkeul/domain/User.java, src/main/java/com/umc/yeongkkeul/domain/enums/ReasonCode.java, src/main/java/com/umc/yeongkkeul/repository/ExpenseRepository.java, src/main/java/com/umc/yeongkkeul/repository/RewardRepository.java, src/main/java/com/umc/yeongkkeul/service/MyPageCommandService.java, src/main/java/com/umc/yeongkkeul/service/MyPageQueryService.java, src/main/java/com/umc/yeongkkeul/web/controller/MyPageController.java, src/main/java/com/umc/yeongkkeul/web/dto/MyPageInfoRequestDto.java, src/main/java/com/umc/yeongkkeul/web/dto/MyPageInfoResponseDto.java, src/main/java/com/umc/yeongkkeul/web/dto/RewardResponseDto.java, src/main/java/com/umc/yeongkkeul/web/dto/UserReferralCodeResponseDto.java
#17 
마이페이지 관련 api 구현
- 유저 정보 수정,조회 
- 추천인 코드 조회
- 리워드 목록 조회
- 필요시 관련 엔티티 수정
=> feat: 마이페이지 api 구현 #17

src/main/java/com/umc/yeongkkeul/apiPayload/code/status/ErrorStatus.java
ex) #이슈번호, 
- ErrorStatus 중복 -> 충돌 이야기 해봐야할듯 함
=> FIX: "ErrorStatus 중복 삭제"

src/main/java/com/umc/yeongkkeul/web/controller/ExpenseController.java, src/main/java/com/umc/yeongkkeul/web/controller/HomeController.java
- 홈 조회, 지출 생성,수정,삭제 API url 수정
=> fix: 홈 관련 API url 수정

.ebextensions-dev/00-makeFiles.config, .ebextensions-dev/01-set-timezone.config, .ebextensions-dev/02-files.config, .github/workflows/deploy-dev.yml, .platform/nginx.conf, .platform/nginx/conf.d/client_max_body_size.conf, Procfile, build.gradle, src/main/resources/application.yml
#31
- ci/cd 파이프라인 구축
- github actions을 위한 deploy-dev.yml 작성
- ElasticBeanstalk 설정 및 연동
- nginx 설정
=> feat: CI/CD 파이프라인 구축 #31

src/main/java/com/umc/yeongkkeul/web/controller/HealthCheckController.java
#31
- pr, merge 후 ci/cd 작동하면서 EC2 배포 및 정상 작동 확인을 위한 GET api입니다
=> feat: healthCheck api #31

src/main/java/com/umc/yeongkkeul/config/SecurityConfig.java
#31
- /health api security 권한 설정 추가 (health check 위함)
=> feat: /health api 권한 설정 추가 #31

src/main/java/com/umc/yeongkkeul/web/controller/CategoryController.java
#32 
- 하드코딩된 userId 수정 - Principal 기반
- Swagger 명세
=> feat: 카테고리 관련 api 수정 및 Swagger 명세 추가 #32

build.gradle, src/main/java/com/umc/yeongkkeul/config/SecurityConfig.java, src/main/java/com/umc/yeongkkeul/repository/UserRepository.java, src/main/java/com/umc/yeongkkeul/repository/UserTermsRepository.java, src/main/java/com/umc/yeongkkeul/service/GoogleLoginService.java, src/main/java/com/umc/yeongkkeul/service/KakaoLoginService.java, src/main/java/com/umc/yeongkkeul/web/controller/UserController.java, src/main/java/com/umc/yeongkkeul/web/dto/GoogleInfoResponseDto.java, src/main/java/com/umc/yeongkkeul/web/dto/GoogleTokenDto.java, src/main/java/com/umc/yeongkkeul/web/dto/GoogleTokenResponseDto.java, src/main/java/com/umc/yeongkkeul/web/dto/SocialInfoResponseDto.java
ex) #5
- 구글 로그인 구현 id token 방식
=> FEAT: "Google 로그인 구현"

src/main/java/com/umc/yeongkkeul/converter/PurchaseConverter.java, src/main/java/com/umc/yeongkkeul/domain/Item.java, src/main/java/com/umc/yeongkkeul/domain/mapping/Purchase.java, src/main/java/com/umc/yeongkkeul/service/HomeQueryServiceImpl.java, src/main/java/com/umc/yeongkkeul/web/controller/HomeController.java, src/main/java/com/umc/yeongkkeul/web/dto/PurchaseResponseDTO.java
=> fix: 홈 - mySkin 부분 수정

src/main/resources/application.yml
=> 50 bug applicationyml 수정

src/main/java/com/umc/yeongkkeul/apiPayload/code/status/ErrorStatus.java, src/main/java/com/umc/yeongkkeul/domain/Item.java, src/main/java/com/umc/yeongkkeul/domain/enums/ItemType.java, src/main/java/com/umc/yeongkkeul/domain/mapping/Purchase.java, src/main/java/com/umc/yeongkkeul/repository/ItemRepository.java, src/main/java/com/umc/yeongkkeul/repository/PurchaseRepository.java, src/main/java/com/umc/yeongkkeul/service/StoreService.java, src/main/java/com/umc/yeongkkeul/web/controller/StoreController.java, src/main/java/com/umc/yeongkkeul/web/dto/PurchaseRequestDto.java, src/main/java/com/umc/yeongkkeul/web/dto/StoreResponseDto.java
ex) #46 
- 상점 조회 api 구현 + 스킨 확인
- 스킨 구매 api 구현
- 스킨 착용 (저장) api 추가 구현(명세 완료)
=> FEAT: 아이템 별 상점 조회, 스킨 확인, 스킨 구매, 스킨 착용(저장) api 구현

src/main/java/com/umc/yeongkkeul/service/StoreService.java
=> FIX: "mySkin ImgUrl 추가"

src/main/java/com/umc/yeongkkeul/apiPayload/code/status/ErrorStatus.java, src/main/java/com/umc/yeongkkeul/domain/UserExitReason.java, src/main/java/com/umc/yeongkkeul/domain/enums/ExitReason.java, src/main/java/com/umc/yeongkkeul/repository/UserExitReasonRepository.java, src/main/java/com/umc/yeongkkeul/service/MyPageCommandService.java, src/main/java/com/umc/yeongkkeul/web/controller/MyPageController.java, src/main/java/com/umc/yeongkkeul/web/dto/MyPageInfoResponseDto.java, src/main/java/com/umc/yeongkkeul/web/dto/UserExitRequestDto.java
#43
-  마이페이지 관련 API 수정 (userId 지우고 토큰 인증)
- 회원 탈퇴 구현 (탈퇴 사유 입력 받고 해당 사용자 관련 데이터 삭제)
=> feat: 마이페이지 api 수정 #43

src/main/java/com/umc/yeongkkeul/repository/CategoryRepository.java, src/main/java/com/umc/yeongkkeul/service/ExpenseCommandService.java, src/main/java/com/umc/yeongkkeul/service/ExpenseCommandServiceImpl.java, src/main/java/com/umc/yeongkkeul/web/controller/ExpenseController.java, src/main/java/com/umc/yeongkkeul/web/dto/ExpenseRequestDTO.java
- 지출 생성 및 수정 api categoryName을 categoryId로 수정하였습니다
- 지출 수정 api requestBody 수정
=> fix: 지출 생성 및 수정 categoryName을 categoryId로 수정, 지출 수정 requestBody 수정

build.gradle, src/main/java/com/umc/yeongkkeul/aws/s3/AmazonS3Manager.java, src/main/java/com/umc/yeongkkeul/config/AmazonConfig.java, src/main/java/com/umc/yeongkkeul/domain/common/Uuid.java, src/main/java/com/umc/yeongkkeul/repository/UuidRepository.java, src/main/resources/application.yml
#42 
- AmazonConfig를 구성하여, S3 액세스키를 기반한 원격접속(put, get 권한)
- AmazonManager를 구현하여 put, get 기능 구현(사진 업로드, url 가져오기)
=> feat: s3 설정 및 사진 추가 로직 구현 #42

src/main/java/com/umc/yeongkkeul/converter/NotificationConverter.java, src/main/java/com/umc/yeongkkeul/web/dto/NotificationDetailsResponseDto.java
=> [FIX] 알림 조회 시간 수정

src/main/java/com/umc/yeongkkeul/converter/NotificationConverter.java
=> [FIX] 알림 조회 시간 초단위 수정

src/main/java/com/umc/yeongkkeul/repository/RewardRepository.java, src/main/java/com/umc/yeongkkeul/service/ExpenseQueryServiceImpl.java, src/main/java/com/umc/yeongkkeul/web/controller/ExpenseController.java, src/main/java/com/umc/yeongkkeul/web/dto/ExpenseResponseDTO.java
=> feat: 지출 - 월간 달력 조회 api 구현

src/main/java/com/umc/yeongkkeul/service/ChatService.java, src/main/java/com/umc/yeongkkeul/web/controller/ChatController.java
=> 75 refactor 채팅 1순위 api 리팩토링

build.gradle, src/main/java/com/umc/yeongkkeul/batch/BatchScheduler.java, src/main/java/com/umc/yeongkkeul/batch/UserScoreBatchConfig.java, src/main/java/com/umc/yeongkkeul/domain/mapping/ChatRoomMembership.java, src/main/java/com/umc/yeongkkeul/repository/ChatRoomMembershipRepository.java, src/main/java/com/umc/yeongkkeul/web/controller/UserController.java
ex) #이슈번호, #5 
- 인가코드를 통해 생성된 accesstoken을 안드로이드한테 받아 테스트 진행
- SpringBatch 구현중 (채팅 방 내 사용자 점수 갱신 시스템 구현) 테스트 미진행 데이터 필요
=> FIX,FEAT: 카카오 인가코드 방식이 아닌 AccessToken 방식으로 로그인 ,SpringBatch 채팅방 내 사용자 점수 갱신(테스트 진행중)

src/main/java/com/umc/yeongkkeul/YeongkkeulApplication.java, src/main/java/com/umc/yeongkkeul/batch/BatchScheduler.java, src/main/java/com/umc/yeongkkeul/batch/UserScoreBatchConfig.java, src/main/java/com/umc/yeongkkeul/domain/mapping/ChatRoomMembership.java
- 채팅방 내부 사용자 점수 갱신 시스템
- Spring Batch 사용
=> FEAT:"사용자 채팅방 내부 점수 갱신 시스템 Spring Batch"

src/main/java/com/umc/yeongkkeul/batch/BatchScheduler.java, src/main/java/com/umc/yeongkkeul/batch/ChatRoomScoreBatchConfig.java, src/main/java/com/umc/yeongkkeul/domain/ChatRoom.java, src/main/java/com/umc/yeongkkeul/domain/mapping/ChatRoomMembership.java, src/main/java/com/umc/yeongkkeul/repository/ChatRoomMembershipRepository.java
#67 
- 사용자 점수 통해 채팅방 점수 갱신 (Spring batch)
=> feat: 채팅방 점수 갱신 (Batch) #67

src/main/java/com/umc/yeongkkeul/batch/BatchScheduler.java, src/main/java/com/umc/yeongkkeul/batch/UserScoreBatchConfig.java
- 하나의 유저가 여러개의 ChatRoomMembership에 userScore 갱신으로 수정
=> FIX:"사용자 채팅방 내부 점수 갱신 시스템 Spring Batch"

src/main/java/com/umc/yeongkkeul/repository/NotificationRepository.java, src/main/java/com/umc/yeongkkeul/web/controller/ChatAPIController.java
=> [FIX] 채팅 API 반환 타입 변경

src/main/java/com/umc/yeongkkeul/aws/s3/AmazonS3Manager.java
#85 
- s3 upload manager의 MIME기반 타입 메타데이터 추가
=> fix: s3 upload manager의 MIME기반 타입 메타데이터 추가

src/main/java/com/umc/yeongkkeul/service/GoogleLoginService.java, src/main/java/com/umc/yeongkkeul/service/KakaoLoginService.java, src/main/java/com/umc/yeongkkeul/service/StoreService.java, src/main/java/com/umc/yeongkkeul/service/UserService.java, src/main/java/com/umc/yeongkkeul/web/controller/UserController.java
ex) #이슈번호, #5 
- 로그아웃 구현
- 스킨 착용 로직 수정 (착용 안 한 스킨 isUser False)
=> FEAT,FIX:"로그아웃, 스킨 착용 로직 수정"

src/main/java/com/umc/yeongkkeul/apiPayload/code/status/ErrorStatus.java, src/main/java/com/umc/yeongkkeul/apiPayload/exception/handler/ChatRoomMembershipHandler.java, src/main/java/com/umc/yeongkkeul/domain/ChatRoom.java, src/main/java/com/umc/yeongkkeul/domain/mapping/ChatRoomMembership.java, src/main/java/com/umc/yeongkkeul/repository/ChatRoomMembershipRepository.java, src/main/java/com/umc/yeongkkeul/repository/ChatRoomRepository.java, src/main/java/com/umc/yeongkkeul/service/ChatService.java, src/main/java/com/umc/yeongkkeul/web/controller/ChatAPIController.java, src/main/java/com/umc/yeongkkeul/web/controller/ChatController.java, src/main/java/com/umc/yeongkkeul/web/dto/chat/PublicChatRoomsDetailResponseDto.java
#79
- 병합한 부분이 있는데 누락된 부분이 있으면 말해주세요.
- 테스트가 안끝난 부분이 있어서 제가 머지하겠습니다!
=> [FEAT] 채팅방 2 3순위 api

src/main/java/com/umc/yeongkkeul/converter/CategoryConverter.java, src/main/java/com/umc/yeongkkeul/web/dto/ExpenseResponseDTO.java
#100 
- 지출 목록 조회 시 지출 id도 리턴하도록 수정
=> fix: 지출 목록 조회 시 지출 id 리턴하도록 수정

src/main/java/com/umc/yeongkkeul/batch/BatchScheduler.java, src/main/java/com/umc/yeongkkeul/domain/enums/AgeGroup.java, src/main/java/com/umc/yeongkkeul/domain/enums/Job.java, src/main/java/com/umc/yeongkkeul/repository/ChatRoomMembershipRepository.java, src/main/java/com/umc/yeongkkeul/repository/ChatRoomRepository.java, src/main/java/com/umc/yeongkkeul/repository/ExpenseRepository.java, src/main/java/com/umc/yeongkkeul/service/ChatRoomQueryService.java, src/main/java/com/umc/yeongkkeul/web/controller/ChatRoomController.java, src/main/java/com/umc/yeongkkeul/web/dto/BannerResponseDto.java
#62 
- 채팅방 배너 조회 api 구현
아직 충분한 데이터로 테스트를 안 해봐서 데이터 쌓으면서 코드 수정할 예정 (채팅방 간 채팅방 백분위 수 관련)
=> feat: 채팅방 배너 조회 api 구현 #62

src/main/java/com/umc/yeongkkeul/repository/ChatRoomRepository.java, src/main/java/com/umc/yeongkkeul/service/ChatService.java, src/main/java/com/umc/yeongkkeul/web/controller/ChatAPIController.java
=> [FIX] 채팅방 둘러보기 정렬 수정

src/main/java/com/umc/yeongkkeul/apiPayload/code/status/ErrorStatus.java, src/main/java/com/umc/yeongkkeul/service/ChatService.java, src/main/java/com/umc/yeongkkeul/web/controller/ChatAPIController.java, src/main/java/com/umc/yeongkkeul/web/dto/chat/ChatRoomDetailRequestDto.java
#111 
- 채팅방 방장이 채팅방 정보를 수정하는 api 구현
=> feat: 방장용 채팅방 정보 수정 api 구현

src/main/java/com/umc/yeongkkeul/web/controller/ExpenseController.java
#117 
- 지출내역 생성시, 해당 유저가 참여한 모든 채팅방을 stream으로 조회하며 지출내역 id를 content로 지니는 영수증 채팅 메시지를 채팅방마다 전송 + 저장하는 로직 추가
=> feat: 지출내역 생성시, 영수증 채팅방마다 stream으로 전송

src/main/java/com/umc/yeongkkeul/service/ExpenseQueryServiceImpl.java
#126 
- 주간 지출 조회 - 하루 목표 지출액 반환 수정
- 주간 지출 통계 조회 - 하루 평균 지출액 반환 수정
=> fix: 주간 지출, 주간 통계 조회 수정

src/main/java/com/umc/yeongkkeul/service/ChatService.java, src/main/java/com/umc/yeongkkeul/web/controller/ExpenseController.java
#128 
- 영수증 전송 로직 컨트롤러에서 서비스로 이전
=> refactor: 영수증 전송 로직 서비스로 분리

src/main/java/com/umc/yeongkkeul/service/ChatService.java, src/main/java/com/umc/yeongkkeul/web/controller/ChatController.java
#123 
- 채팅방/방장용 - 특정 유저 내보내기 api 구현
=> feat:  방장용 채팅방 내보내기 api 구현

src/main/java/com/umc/yeongkkeul/security/TokenProvider.java
#131 
- 프론트 측 리프레시 토큰 테스트 위한 액세스 토큰 유효기간 단축
=> test: 프론트 측 리프레시 토큰 테스트 위한 액세스 토큰 유효기간 단축

src/main/java/com/umc/yeongkkeul/security/TokenProvider.java
#132 
- 테스트 완료로 인한 액세스 토큰 만료시간 정상화
=> Fix: 테스트 완료로 인한 정상화

src/main/java/com/umc/yeongkkeul/repository/RewardRepository.java, src/main/java/com/umc/yeongkkeul/service/HomeQueryService.java, src/main/java/com/umc/yeongkkeul/service/HomeQueryServiceImpl.java, src/main/java/com/umc/yeongkkeul/web/controller/HomeController.java, src/main/java/com/umc/yeongkkeul/web/dto/HomeResponseDTO.java
#143 
- 홈 - 전날 획득한 리워드 조회 api 구현
=> [FEATURE] 홈 - 전날 획득한 리워드 조회 api 구현

src/main/java/com/umc/yeongkkeul/aws/s3/AmazonS3Manager.java, src/main/java/com/umc/yeongkkeul/config/AmazonConfig.java, src/main/java/com/umc/yeongkkeul/converter/ExpenseConverter.java, src/main/java/com/umc/yeongkkeul/service/ExpenseCommandService.java, src/main/java/com/umc/yeongkkeul/service/ExpenseCommandServiceImpl.java, src/main/java/com/umc/yeongkkeul/web/controller/ExpenseController.java, src/main/java/com/umc/yeongkkeul/web/dto/ExpenseRequestDTO.java
=> [FIX] 지출 내역 이미지 저장 부분 수정

src/main/java/com/umc/yeongkkeul/converter/ChatRoomConverter.java, src/main/java/com/umc/yeongkkeul/web/dto/chat/ChatRoomDetailResponseDto.java
=> [FEAT] 채팅방 둘러보기   랭킹 조회 부분 추가

src/main/java/com/umc/yeongkkeul/service/ChatService.java
=> [FIX] 비밀번호 로직 수정

src/main/java/com/umc/yeongkkeul/web/controller/StoreController.java, src/main/java/com/umc/yeongkkeul/web/controller/UserController.java
=> FIX: "2차 피드백 url 명명"

src/main/java/com/umc/yeongkkeul/web/controller/ExpenseController.java
#151 
- 2차 피드백 - expense url 수정
=> [FIX] 2차 피드백 expense url 수정

src/main/java/com/umc/yeongkkeul/converter/ChatRoomConverter.java, src/main/java/com/umc/yeongkkeul/service/ChatService.java, src/main/java/com/umc/yeongkkeul/web/controller/ChatAPIController.java, src/main/java/com/umc/yeongkkeul/web/dto/chat/ChatRoomDetailRequestDto.java
#156 
- ChatRoomDetailRequestDto에서 url 삭제
- 컨트롤러 단에서 chatRoomImage 필드에 이미지 파일을 추가할 수 있도록 변경
- 서비스 로직 상에서 이미지 입력이 필수가 아니므로 빈 값이라면, 기본 이미지 적용
=> feat: 채팅방 생성 시 url이 아닌 이미지 입력하도록 변경

src/main/java/com/umc/yeongkkeul/service/ExpenseCommandServiceImpl.java
=> fix: 지출 수정 API 사진 부분 수정

src/main/java/com/umc/yeongkkeul/service/StoreService.java
- 사용자 스킨(홈화면,상점 조회)에서 저장 인코딩 변경
- 상품명으로만 인코딩해서 저장하면  접근제한이 걸림
=> FIX: "사용자 홈화면 스킨 저장 인코딩 변경"

src/main/java/com/umc/yeongkkeul/batch/BatchScheduler.java, src/main/java/com/umc/yeongkkeul/batch/RewardNotificationBatchConfig.java, src/main/java/com/umc/yeongkkeul/repository/ChatRoomMembershipRepository.java
=> "FEAT": 리워드 지급 및 알림 구현

src/main/java/com/umc/yeongkkeul/converter/ChatRoomConverter.java, src/main/java/com/umc/yeongkkeul/service/ChatService.java, src/main/java/com/umc/yeongkkeul/web/controller/ChatAPIController.java
=> [FIX] 채팅방 생성 초기값 변경

src/main/java/com/umc/yeongkkeul/repository/NotificationReadRepository.java, src/main/java/com/umc/yeongkkeul/service/NotificationService.java
#174 
- 하루 목표 지출액 초과 알림 - 처음 한 번만 발생 후 중복 생성 안되도록 수정
=> 174 feature 하루 목표 지출액 초과 알림 생성

src/main/java/com/umc/yeongkkeul/apiPayload/code/status/ErrorStatus.java, src/main/java/com/umc/yeongkkeul/service/ChatService.java, src/main/java/com/umc/yeongkkeul/web/controller/ChatController.java
=> [BUG] 채팅방 입장/퇴장 버그 수정

src/main/java/com/umc/yeongkkeul/repository/UserRepository.java, src/main/java/com/umc/yeongkkeul/service/GoogleLoginService.java, src/main/java/com/umc/yeongkkeul/service/KakaoLoginService.java
=> FIX: "소셜 로그인 에러 처리 보안"

src/main/java/com/umc/yeongkkeul/service/ChatService.java, src/main/java/com/umc/yeongkkeul/web/controller/ChatAPIController.java, src/main/java/com/umc/yeongkkeul/web/dto/chat/ChatSettingResponseDto.java
=> [FIX] 동기화 로직 변경
